version: '3.8'

services:
  backend:
    image: python:3.11
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "2024:2024"
    # environment:
    #   - REDIS_URL=redis://redis:6379/0
    command: sh -c "pip install -e . && langgraph dev --host 0.0.0.0 --port 2024 --no-browser"

  frontend:
    image: node:20
    working_dir: /app/mobile-app
    volumes:
      - ./mobile-app:/app/mobile-app
      - /app/mobile-app/node_modules
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    environment:
      - EXPO_DEV_SERVER_LISTEN_ADDRESS=0.0.0.0
      - EXPO_DEV_TOOLS_LISTEN_ADDRESS=0.0.0.0
    command: sh -c "npm install && npx expo start"

  # redis:
  #   image: redis:7
  #   restart: unless-stopped
