name: EAS Deploy Web on Main Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: mobile-app

      - name: Install EAS CLI
        run: npm install --global eas-cli

      - name: Export web build
        run: npx expo export --platform web
        working-directory: mobile-app
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: EAS Deploy (Production)
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: eas deploy --prod --non-interactive
        working-directory: mobile-app